version: '2'

services:

    mongo:
      image: mongo:latest
      # env_file: .env
      ports:
        - 27017:27017
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=pass
        - MONGO_INITDB_DATABASE=dev
      container_name: dev-db
      restart: always
      privileged: true
      volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
